# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('-created',)},
        ),
    ]
