# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='resume',
            field=models.TextField(),
        ),
    ]
