# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='news_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
