# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='devlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='BugRecord',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='category',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tag',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='devlogcomments',
            name='diaries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dev_log.Tutorial'),
        ),
    ]
