# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_log', '0002_auto_20180606_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tag',
            field=models.TextField(),
        ),
    ]
