# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_log', '0003_auto_20180606_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='resume',
            field=models.TextField(default='1'),
        ),
    ]
