# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_log', '0006_tutorial_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='language',
            field=models.TextField(default='1'),
        ),
    ]
