# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_log', '0007_tutorial_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='language',
            field=models.TextField(),
        ),
    ]
